name: github matrix
on:
    push:
        branches:
            - master
jobs:
    first_job:
        strategy:
            matrix:
                operating syatem: [ubuntu-latest, windows-latest]
        runs-on: ubuntu-latest
        steps:
            - name: first action
              run: echo "job accomplished"
