name: github matrix
on:
    push:
        branches:
            - master
jobs:
    first_job:
        strategy:
            matrix:
                operating-system: [ubuntu-latest, windows-latest]
        runs-on: ${{ matrix.operating-system }}
        steps:
            - name: first action
              run: echo "job accomplished"
            - name: repeat
              run: echo "repeat composite custom github action"
